services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildFilter:
      paths:
        - Dockerfile
        - '**/*.php'
        - composer.*
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - fromGroup: laravel-db
